# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XPolo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XPolo
    pod 'AFNetworking', '~> 2.6'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'BFKit-Swift'

  target 'XPoloTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XPoloUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
